### ISSUE TITLE
Audit & images in body

### ISSUE THREAD

**Issue by zzrez** [saigowthamr/gatsby-advanced-starter#5]
Your starter is excellent and I have been testing it out for a couple of days now. But 2 issues:-
1) I ran npm audit fix. This completely ruined it, and "gatsby develop" threw out endless errors. So I had to download the starter again. But why the problem ?
2) Handling of images was my main focus. This works well for frontmatter. Any chance you can show how images in the body can also be processed with gatsby-image similarly?

**Comment by zzrez** [comment]
Re 2, got this to work by adding plugin gatsby-remark-images to gatsby-transformer-remark:-

`{
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          `gatsby-remark-prismjs`, 
          {
            resolve: `gatsby-remark-images`,
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 590,
            },
          },
        ]
      }
    },`

**Comment by saigowthamr** [comment]
yeah `gatsby-remark images` plugin is used to work with markdown images.
